#!/bin/bash

#--DEFINE VARIABLES--#

# Set Appdata Directory
appdataDirectory='/PATH/TO/YOUR/DOCKER/APPDATA'

# Set Backup Directory
backupDirectory='/PATH/TO/YOUR/BACKUP/DIRECTORY/'

# Set Number of Days to Keep Backups 
days=60


#--START SCRIPT--#
/usr/local/emhttp/plugins/dynamix/scripts/notify -s "AppData Backup" -d "Backup of ALL Appdata starting."

now="$(date +"%Y-%m-%d"@%H.%M)" 
mkdir """$backupDirectory"""$now""

for path in "$appdataDirectory"*

do
    name="$(basename "$path")"
    path=""$appdataDirectory""$name""
 
    cRunning="$(docker ps -a --format '{{.Names}}' -f status=running)"

    if echo $cRunning | grep -iqF $name; then
    echo "Stopping $name"
        docker stop -t 60 "$name"
        tar cWfC "./$name.tar" "$(dirname "$path")" "$(basename "$path")"
    echo "Starting $name"
        docker start "$name"
    else
        tar cWfC "./$name.tar" "$(dirname "$path")" "$(basename "$path")"
    echo "$name was stopped before backup, ignoring startup"
    fi
 
    cp -a "$name.tar" """$backupDirectory"""$now""
    rm "$name.tar"
done

#Cleanup Old Backups
#--START SCRIPT--#
/usr/local/emhttp/plugins/dynamix/scripts/notify -s "AppData Backup" -d "Backup of ALL Appdata starting."

now="$(date +"%Y-%m-%d"@%H.%M)" 
mkdir """$backupDirectory"""$now""

for path in "$appdataDirectory"*

do
    name="$(basename "$path")"
    path=""$appdataDirectory""$name""
 
    cRunning="$(docker ps -a --format '{{.Names}}' -f status=running)"

    if echo $cRunning | grep -iqF $name; then
    echo "Stopping $name"
        docker stop -t 60 "$name"
        tar cWfC "./$name.tar" "$(dirname "$path")" "$(basename "$path")"
    echo "Starting $name"
        docker start "$name"
    else
        tar cWfC "./$name.tar" "$(dirname "$path")" "$(basename "$path")"
    echo "$name was stopped before backup, ignoring startup"
    fi
 
    cp -a "$name.tar" """$backupDirectory"""$now""
    rm "$name.tar"
done

#Cleanup Old Backups
find "$backupDirectory"* -type d -mtime +"$days" -exec rm -rf {} +

#Stop Notification
/usr/local/emhttp/plugins/dynamix/scripts/notify -s "AppData Backup" -d "Backup of ALL Appdata complete."
