#!/bin/bash

#--DEFINE VARIABLES--#

# Containers to backup and their appdata paths
list=(
    container01_name    /path/to/docker/appdata/container01_name
    container02_name    /path/to/docker/appdata/container01_name
    container03_name    /path/to/docker/appdata/container01_name
)

# Set Backup Directory
backupDirectory='/path/to/your/backup/directory/'

# Set Number of Days to Keep Backups 
days=60
 
#--START SCRIPT--#
/usr/local/emhttp/plugins/dynamix/scripts/notify -s "AppData Backup" -d "Backup of ALL Appdata starting."

now="$(date +"%Y-%m-%d"@%H.%M)"
 
mkdir ""$backupDirectory""$now""
 
for (( i = 0; i < ${#list[@]}; i += 2 ))
do
    name=${list[i]} path=${list[i+1]}
 
    cRunning="$(docker ps -a --format '{{.Names}}' -f status=running)"

    if echo $cRunning | grep -iqF $name; then
    echo "Stopping $name"
        docker stop -t 60 "$name"
        tar cWfC "./$name.tar" "$(dirname "$path")" "$(basename "$path")"
    echo "Starting $name"
        docker start "$name"
    else
        tar cWfC "./$name.tar" "$(dirname "$path")" "$(basename "$path")"
    echo "$name was stopped before backup, ignoring startup"
    fi
 
    cp -a "$name.tar" ""$backupDirectory""$now""
    rm "$name.tar"
done

#Cleanup Old Backups
find "$backupDirectory"* -type d -mtime +"$days" | xargs rm -rf

#Stop Notification
/usr/local/emhttp/plugins/dynamix/scripts/notify -s "AppData Backup" -d "Backup of CRITICAL Appdata complete."
